# build-and-test.yml
#
# Dispatch workflow for build-and-test-callable.yml

name: B+T dispatcher

on:
  workflow_dispatch:
    inputs:
      test_all:
        description: 'Test all options. If set to false, will only trigger the CI for the default options.'
        default: false
        type: boolean
  pull_request:

jobs:
  # -------------------------------------------------------------------------------------------------
  # Build and test whole matrix of options on linux
  # -------------------------------------------------------------------------------------------------
  test-linux:
    if: ${{ github.event_name == 'pull_request' || inputs.test_all == true }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11'] # 3.12 is not supported by scipy
        mfem-branch: [master, default] # 'default' uses a specific commit hash defined in setup.py:repos_sha
        parallel: [false, true]
    name: ${{ matrix.name }}
    uses: ./.github/workflows/build-and-test-callable.yml
    with:
      os: ubuntu-latest
      python-version: ${{ matrix.python-version }}
      mfem-branch: ${{ matrix.mfem-branch }}
      parallel: ${{ matrix.parallel }}


  # -------------------------------------------------------------------------------------------------
  # Specific cases (we want these to use defaults, and not expand the dimensions of the matrix)
  # -------------------------------------------------------------------------------------------------
  test-macos:
    if: ${{ github.event_name == 'pull_request' || inputs.test_all == true }}
    strategy:
      fail-fast: false
      matrix:
        mfem-branch: [master, default]
    name: " "
    uses: ./.github/workflows/build-and-test-callable.yml
    with:
      os: macos-latest
      mfem-branch: ${{ matrix.mfem-branch }}

  test-cuda:
    if: ${{ github.event_name == 'pull_request' || inputs.test_all == true }}
    uses: ./.github/workflows/build-and-test-callable.yml
    with:
      cuda: true
    name: " "

  test-libceed:
    if: ${{ github.event_name == 'pull_request' || inputs.test_all == true }}
    uses: ./.github/workflows/build-and-test-callable.yml
    with:
      libceed: true
    name: " "

  test-gslib:
    if: ${{ github.event_name == 'pull_request' || inputs.test_all == true }}
    uses: ./.github/workflows/build-and-test-callable.yml
    with:
      gslib: true
    name: " "

  # -------------------------------------------------------------------------------------------------
  # Build and test defaults
  # -------------------------------------------------------------------------------------------------
  test-defaults:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.test_all == false }}
    uses: ./.github/workflows/build-and-test-callable.yml