# This is a clean-up/refactor of test_with_MFEM_release.yml
name: Build and Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test:
    # if: contains(github.event.pull_request.labels.*.name, 'in-test-with-mfem-release')
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        #, macos-latest]
        python-version: [3.9]
        #"3.7", "3.8", "3.9", "3.10"]

        # right now, default is a hardcoded sha defined in setup.py:repos_sha
        mfem-branch: [master, default]
        parallel: [false, true]
        cuda: [false, true]
        libceed: [false]
        gslib: [true]
        # When phases==true, run each individual build step explicitly: mfem -> swig -> pymfem
        phases: [false]

        exclude:
          # CUDA does not support MacOS
          - os: macos-latest
            cuda: true
        include:
          # Include a single example where the build is executed in phases
          - os: ubuntu-latest
            python-version: 3.9
            mfem-branch: default
            parallel: false
            cuda: false
            libceed: false
            gslib: true
            phases: true

    runs-on: ${{ matrix.os }}

    # https://7tonshark.com/posts/github-actions-ternary-operator/
    name: >-
      ${{ matrix.os }},
      ${{ matrix.python-version }},
      ${{ matrix.mfem-branch }},
      (${{ matrix.parallel && 'parallel' || 'serial' }}${{ matrix.cuda && ' + cuda' || '' }}${{ matrix.libceed && ' + libceed' || '' }}${{ matrix.gslib && ' + gslib' || '' }})

    env:
       CUDA: "11.5"
       build-flags: >-
        ${{ matrix.parallel && '--with-parallel' || '' }}
        ${{ matrix.cuda && '--with-cuda' || '' }}
        ${{ matrix.libceed && '--with-libceed' || '' }}
        ${{ matrix.gslib && '--with-gslib' || '' }}
        ${{ (!(matrix.mfem-branch == 'default') && format('--mfem-branch={0}', matrix.mfem-branch)) || '' }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install core dependencies via requirements.txt
      run: |
        pip install -r requirements.txt --verbose

    - name: Install CUDA
      if: ${{ matrix.cuda == true }}
      run: |
        wget -q https://developer.download.nvidia.com/compute/cuda/12.4.1/local_installers/cuda_12.4.1_550.54.15_linux.run
        sudo chmod +x cuda_12.4.1_550.54.15_linux.run
        sudo ./cuda_12.4.1_550.54.15_linux.run --silent

    - name: Install MPI
      if: ${{ matrix.parallel == true }}
      run: |
        sudo apt-get install mpich libmpich-dev
        pip install mpi4py

    - name: Print python package versions
      run: |
        pip list

    - name: Build (phases)
      if: ${{ matrix.phases == true }}
      run: |
        # test workflow to manually run swig
        python setup.py clean --swig
        python setup.py install --ext-only --verbose ${{ env.build-flags }}
        python setup.py install --swig --verbose ${{ env.build-flags }}
        python setup.py install --skip-ext --skip-swig --verbose ${{ env.build-flags }}

    - name: Build
      if: ${{ matrix.phases == false }}
      run: |
        python setup.py install ${{ env.build-flags }}

    - name: Run serial
      if: ${{ matrix.parallel == false }}
      run: |
        cd test
        python run_examples.py -serial -verbose
    - name: Run parallel
      if: ${{ matrix.parallel == true }}
      run: |
        cd test
        python run_examples.py -parallel -verbose -np 2

    - name: Generate test results artifact
      run: |
        tar -cvzf sandbox.tar.gz test/sandbox

    - name: Generate artifact name
      id: generate-artifact-name
      run: |
        txt=$(python -c "import datetime;print(datetime.datetime.now().strftime('%H_%M_%S_%f'))")
        name="test_results_"${txt}"_"${{ github.run_id }}".tar.gz"
        echo "name=${name}" >> $GITHUB_OUTPUT

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: failure()
      with:
          name: ${{ steps.generate-artifact-name.outputs.name }}
          path: sandbox.tar.gz
          retention-days: 1
