name: main

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest]
        env:
           #- { USE_CUDA_PARALLEL: "00"}
           - { USE_CUDA_PARALLEL: "10"}
           - { USE_CUDA_PARALLEL: "01"}
           #- { USE_CUDA_PARALLEL: "11"}

        include:
           - os: macos-latest
             python-version: 3.6
             env: {USE_CUDA_PARALLEL: "00"}
#
    runs-on: ${{ matrix.os }}	   
    #env: ${{ matrix.env }}
    env: 
       USE_CUDA_PARALLEL: ${{ matrix.env.USE_CUDA_PARALLEL }}
       CUDA: "10.1"
       SANDBOX: ~/sandbox
       PYTHONLIB: ~/sandbox/lib/python${{ matrix.python-version }}/site-packages	
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel

        mkdir -p ~/sandbox/lib
        export PYTHONPATH=$PYTHONLIB:$PYTHONPATH
        echo $PYTHONPATH

        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install numpy --prefix=~/sandbox
        ls -l ~/sandbox/lib
        python -c "import numpy;print(numpy.__file__)"	
        pwd
        if [ "${USE_CUDA_PARALLEL}" = "11" ] || [ "${USE_CUDA_PARALLEL}" = "10" ]; then
            echo $cuda
            source ./ci_scripts/add_cuda_10_1.sh;
        fi
        if [ "${USE_CUDA_PARALLEL}" = "01" ] || [ "${USE_CUDA_PARALLEL}" = "11" ]; then
            sudo apt-get install mpich;
            sudo apt-get install libmpich-dev;
            pip install mpi4py --no-cache-dir --prefix=~/sandbox;

            python -c "import mpi4py;print(mpi4py.get_include())";	    
        fi
        ls -l /usr/local/	
        ls -l $PYTHONLIB	
        #pip install flake8 pytest
        
    - name: Build
      run: |
        export PATH=/usr/local/cuda-${CUDA}/bin:$PATH
        export PYTHONPATH=$PYTHONLIB:$PYTHONPATH
        echo $PATH
        echo $PYTHONPATH
        if [ "${USE_CUDA_PARALLEL}" = "00" ]; then  
           python setup.py install --prefix=$SANDBOX
        fi
        if [ "${USE_CUDA_PARALLEL}" = "01" ]; then
           python setup.py install --with-parallel --prefix=$SANDBOX
        fi
        if [ "${USE_CUDA_PARALLEL}" = "10" ]; then
           python setup.py install --with-cuda --prefix=$SANDBOX
        fi
        if [ "${USE_CUDA_PARALLEL}" = "11" ]; then
           python setup.py install --with-cuda --with-paralel --prefix=$SANDBOX
        fi

    - name: EX1_RUN      
      run: |

        export PATH=/usr/local/cuda-${CUDA}/bin:$PATH
        export PYTHONPATH=$PYTHONLIB:$PYTHONPATH
        cd $SANDBOX/test
        echo $PATH
        echo $PYTHONPATH
        if [ "${USE_CUDA_PARALLEL}" = "00" ]; then  
           python ../examples/ex1.py;
        fi
        if [ "${USE_CUDA_PARALLEL}" = "01" ]; then
           which mpicc;
           mpirun -np 2 python ../examples/ex1p.py;    
        fi
        if [ "${USE_CUDA_PARALLEL}" = "10" ]; then
           python ../examples/ex1.py --pa
        fi
        if [ "${USE_CUDA_PARALLEL}" = "11" ]; then
           mpirun -np 2 python ../examples/ex1.py --pa
        fi



