name: release_binary

on:
  push:
    branches: [ release_binary ]
  #pull_request:
  #  branches: [ test ]

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    #container: node:10.16-jessie
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
