name: release_binary

on:
  push:
    branches: [ release_binary ]
  #pull_request:
  #  branches: [ test ]

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    #container: node:10.16-jessie
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
          git clone https://github.com/sshiraiwa/PyMFEM.git
          export PATH=/opt/python/cp36-cp36m/bin:$PATH
          pip3 install numpy
          pip3 install six
          pip3 install auditwheel
          pip3 install twine
          CWD=$PWD
          ls -l 
          cd PyMFEM
          git checkout release_binary
          python3 setup.py install
          rm -rf dist/*
          python3 setup.py bdist_wheel
          export LD_LIBRARY_PATH=${CWD}/PyMFEM/external/mfem/cmbuild_ser/:$LD_LIBRARY_PATH
          rm -rf wheelhouse/*
          auditwheel repair dist/*.whl
          rm -rf dist/*
          python3 setup.py sdist	  
        name: Run in container
